stages:
  - deploy

deploy_crd:
  stage: deploy
  image: docker:latest
  variables:
    KUBECONFIG: $CI_PROJECT_DIR/kubeconfig.yaml
    NAMESPACE_LIST: "namespace1,namespace2,namespace3" # Default namespaces
  script:
    - apk add --no-cache curl
    - curl https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl -o kubectl
    - chmod +x kubectl
    - mkdir -p ~/.kube
    - cp $KUBECONFIG ~/.kube/config
    - cd $CI_PROJECT_DIR # Switch to the project directory
    - |
      sed -e 's|{{NAMESPACE_LIST}}|'"$NAMESPACE_LIST"'|g' crd.yaml | ./kubectl apply -f -
