apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: prometheus-operator
  creationTimestamp: "2023-06-20T13:53:44Z"
  generateName: prometheus-operator-7748694676-
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.63.0
    pod-template-hash: "7748694676"
  name: prometheus-operator-7748694676-ff877
  namespace: monitoring
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: prometheus-operator-7748694676
    uid: 50276180-ff62-4cf1-86d1-605f0c15b33f
  resourceVersion: "3129106"
  uid: 1c60fb7d-5fa9-49dc-b670-e0b198ac76ce
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - --kubelet-service=kube-system/kubelet
    - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0
    image: quay.io/prometheus-operator/prometheus-operator:v0.63.0
    imagePullPolicy: IfNotPresent
    name: prometheus-operator
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2q7dd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-0-251.us-east-2.compute.internal
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccount: prometheus-operator
  serviceAccountName: prometheus-operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2q7dd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-20T13:53:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-21T14:46:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-21T14:46:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-20T13:53:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0e2db39a52640d2c3445d70087cf178d970c6537e308827e9c4351d9cea3df7a
    image: quay.io/prometheus-operator/prometheus-operator:v0.63.0
    imageID: quay.io/prometheus-operator/prometheus-operator@sha256:be4fbe0cfcad639e7a9ce40274917e1e30a3cae045ae27cde35ac84739fdef40
    lastState:
      terminated:
        containerID: containerd://7b6db68d3db65f234d01a9402eabd806aba1303ef34623ad183c0277e21680c0
        exitCode: 1
        finishedAt: "2023-06-21T14:46:13Z"
        reason: Error
        startedAt: "2023-06-21T14:36:13Z"
    name: prometheus-operator
    ready: true
    restartCount: 149
    started: true
    state:
      running:
        startedAt: "2023-06-21T14:46:13Z"
  hostIP: 10.0.0.251
  phase: Running
  podIP: 10.0.0.139
  podIPs:
  - ip: 10.0.0.139
  qosClass: Burstable
  startTime: "2023-06-20T13:53:44Z"