---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: ngix
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.4
        resources:
          requests:
            memory: 2Gi
            cpu: "1"
          limits:
            memory: 2Gi
            cpu: "1"
        ports:
        - containerPort: 80

