---
apiVersion:  monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main 
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-operator
        port: web
  version: v2.42.0
  ServiceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: main 
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring: prometheus