---
apiVersion: v1
kind: Service 
metadata:
  namespace: staging 
  name: myapp-prom 
  labels: 
    app: myapp-monitorng 
spec: 
  type: ClusterIP 
  ports: 
    - name: http-metrics 
      port: 8081
      targetPort: http-metrics
  selector: 
    app: myapp